### PR TITLE
Make tanker work with scope of ActiveRecords

### PR DESCRIPTION
**Pull request by zsxking**
Use where condition instead of the find method to ignore the RecordNotFound errors when using search_tank under scope.

### CODE REVIEW

**Comment by kidpollo** [comment]
This looks cool! but can you add a spec for it and probably some kind of example usage in the reademe?

**Comment by zsxking** [comment]
Sorry for the delay. Just updated the code with spec and example usage in readme.

**Comment by kidpollo** [comment]
Cool I am loving it! One last thing! I wouldnt like to integrate this and break people using tanker with mongoid. I dont have integration specs with mongoid but for the moment could you add some validation that uses respond_to to check that find_by_ids exists and if not use find(ids) ?

**Comment by jbritten** [comment]
I would love, love, love to see this get pulled into master!  Being able to scope the search without getting a bunch of ActiveRecord errors would be awesome :)  Thanks for patching the tanker gem @zsxking!

**Comment by kidpollo** [comment]
Merged, oficial release coming up soon!

**Comment by jbritten** [comment]
Awesome!  Thanks.  Looking forward to a gem update.

**Pull request merged**
